# Model Configuration
model:
  name: "F5TTS_Base"
  repo: "F5-TTS"
  checkpoint_step: 1200000
  config:
    dim: 1024
    depth: 22
    heads: 16
    ff_mult: 2
    text_dim: 512
    conv_layers: 4

# Audio Generation Settings
audio:
  mel_spec_type: "vocos"
  speed: 1.0

# Dataset Settings
dataset:
  dialog_data_path: "hf://datasets/AKCIT-Audio/LIGHT_transcriptions/data/train-00000-of-00001.parquet"
  reference_dataset: "freds0/BRSpeech-TTS-Leni"
  reference_split: "train"

# Output Settings
output:
  base_dir: "generated_audio"  # Default output directory