# Dataset Settings
dataset:
  dialog_data_path: "hf://datasets/AKCIT-Audio/LIGHT_transcriptions/data/train-00000-of-00001.parquet"
  reference_dataset: "freds0/BRSpeech-TTS-Leni"
  reference_split: "train"
